CustomerRelationsManagement/Controllers/CustomerController.cs
using CustomerRelationsManagement.Models;
using CustomerRelationsManagementDomain.Entities;
using CustomerRelationsManagementPersistence.Services;
using CustomerRelationsMangementApplication.DTOs;
using CustomerRelationsMangementApplication.IServices;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CustomerRelationsManagement.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService _customerService;
        private readonly ISuggestionService _suggestionService;
        private readonly UserManager<AppUser> _userManager;
        public CustomerController(ICustomerService customerService, ISuggestionService suggestionService, UserManager<AppUser> userManager)
        {
            _customerService = customerService;
            _suggestionService = suggestionService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {            
            
            var allCustomers = await _customerService.GetAllCustomersAsync();

            return View(new EmployeeModel { allCustomers = allCustomers.ToList()});
        }
        [HttpGet]
        public IActionResult AddCustomer( )
        {
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddCustomer(CreateCustomer customer)
        {
            await _customerService.CreateCustomerAsync(customer);
            ViewBag.SuccessMessage = "Kayıt Başarılı";
            ModelState.Clear();
            return View("AddCustomer");
        }

        [HttpGet]
        [Route("Customer/EditCustomer/{id}")]
        public async Task<IActionResult> EditCustomer(int Id)
        {
            var result = await _customerService.GetCustomerByIdAsync(Id);
            return View("EditCustomer",result);
        }
        [HttpPost]
        //[Route("Customer/EditCustomer/{id}")]
        public  async Task<IActionResult> EditCustomer(Customer customer)
        {
           var result = await _customerService.UpdateCustomer(customer);

            return RedirectToAction("Index","Customer");
        }

        [HttpGet]
        public async Task<IActionResult> MyCustomer()
        {
            var MyCustomers = await _customerService.MyCustomers(User);

                return View("MyCustomer", MyCustomers);
        }


    }
}

CustomerRelationsManagement/Controllers/SuggestionController.cs
using CustomerRelationsManagementDomain.Entities;
using CustomerRelationsMangementApplication.IServices;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CustomerRelationsManagement.Controllers
{
    public class SuggestionController : Controller
    {
        private readonly ISuggestionService _suggestionService;
        private readonly UserManager<AppUser> _userManager;

        public SuggestionController(ISuggestionService suggestionService, UserManager<AppUser> userManager)
        {
            _suggestionService = suggestionService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var result =  await _suggestionService.GetAllSuggestionAsync(User);

            return View(result);
        }

        [HttpGet]
        [Route("Suggestion/AddSuggestion/{id}")]
        public async Task<IActionResult> AddSuggestion(int Id)
        {
            var employeeID = int.Parse(_userManager.GetUserId(User));
            Suggestion suggestion = new() {CustomerId = Id,EmployeeId =employeeID};
            var result = await _suggestionService.CreateSuggestion(suggestion);
            return View(result);
        }

        [HttpPost]
        [Route("Suggestion/AddSuggestion/{id}")]
        public IActionResult AddSuggestion(Suggestion suggestion)
        {
             
              _suggestionService.UpdateSuggestion(suggestion);
            return View(suggestion);
        }
    }
}

CustomerRelationsManagement/Views/Customer/AddCustomer.cshtml
@using CustomerRelationsMangementApplication.DTOs;
@model CreateCustomer

@{
    
    Layout = "../DefaultLayout/Index";
}


<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Müşteri Paneli</h3>
            </div>
            <div class="title_right">
                @if (ViewBag.SuccessMessage != null)
                {
                    <div class="alert alert-success"  role="alert">
                        @ViewBag.SuccessMessage
                    </div>
                }
            </div>
    
        </div>
  

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>CRM<small>Yeni Müşteri</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Settings 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <form class="form-horizontal form-label-left " method="post" novalidate>

                            <span class="section">Müşteri Bilgileri</span>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyName">
                                    Şirket Adı <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="companyName" class="form-control col-md-7 col-xs-12" asp-for="CompanyName" required="required" type="text">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">
                                    Email <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="email" asp-for="Email" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="phone">
                                    İletişim Numarası <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="number" id="phone" asp-for="PhoneNumber"  required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contactPerson">
                                    Görüşülen Kişi <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="contactPerson" asp-for="ContactPerson" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="IsActive">
                                    Aktiflik <span class="required">*</span>
                                </label>
                                <div class="col-md-2 col-sm-2 col-xs-6">
                                    <input type="checkbox" id="IsActive" asp-for="IsActive" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Vazgeç</button>
                                    <button id="send" type="submit" class="btn btn-success">Müşteri Bilgilerini Kaydet</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CustomerRelationsManagement/Views/Customer/EditCustomer.cshtml
@using CustomerRelationsManagementDomain.Entities;
@model Customer

@{
    ViewBag.Title = "aaa";
    Layout = "../DefaultLayout/Index";
}


<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Müşteri Paneli</h3>
            </div>
            <div class="title_right">
                @if (ViewBag.SuccessMessage != null)
                {
                    <div class="alert alert-success" role="alert">
                        @ViewBag.SuccessMessage
                    </div>
                }
            </div>

        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>CRM<small>Yeni Müşteri</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Settings 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <form class="form-horizontal form-label-left " method="post" novalidate>

                            <span class="section">Müşteri Bilgileri</span>

                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="companyName">
                                    Şirket Adı <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input id="companyName" class="form-control col-md-7 col-xs-12" asp-for="CompanyName" required="required" type="text">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">
                                    Email <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="email" asp-for="Email" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="phone">
                                    İletişim Numarası <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="number" id="phone" asp-for="PhoneNumber" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="contactPerson">
                                    Görüşülen Kişi <span class="required">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" id="contactPerson" asp-for="ContactPerson" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>
                            <div class="item form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="IsActive">
                                    Aktiflik <span class="required">*</span>
                                </label>
                                <div class="col-md-2 col-sm-2 col-xs-6">
                                    <input type="checkbox" id="IsActive" asp-for="IsActive" required="required" class="form-control col-md-7 col-xs-12">
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-3">
                                    <button type="submit" class="btn btn-primary">Vazgeç</button>
                                    <button id="send" type="submit" class="btn btn-success">Bilgileri Güncelle</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CustomerRelationsManagement/Views/Customer/Index.cshtml
@model EmployeeModel

@{
    ViewBag.Title = "aaa";
    Layout = "../DefaultLayout/Index";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Müşteri Paneli</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>CRM<small>Müşteriler</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Settings 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <form class="form-horizontal form-label-left " method="post" novalidate>
                            <div class="section" style="margin: 5px;">
                                <h2>Müşteri Listesi</h2>
                                <button>
                                    @Html.ActionLink("Yeni Müşteri", "AddCustomer", null, new { @class = "btn btn-success btn-xl" })
                                </button>

                                <table class="table">
                                    <tr>
                                        <th>
                                            Şirket Adı
                                        </th>
                                        <th>
                                            İletişim Kurulan Kişi
                                        </th>
                                        <th>
                                            Email adresi
                                        </th>
                                        <th>
                                            Telefon Numarası
                                        </th>
                                        <th>

                                        </th>
                                    </tr>

                                    @foreach (var item in Model.allCustomers)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CompanyName)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.ContactPerson)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                                            </td>

                                            <td>
                                                @Html.ActionLink("Bilgileri Düzenle", "EditCustomer", new { Id = item.Id })
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </form>
                   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CustomerRelationsManagement/Views/Customer/MyCustomer.cshtml
@using CustomerRelationsManagementDomain.Entities;
@model List<Customer>

@{
    ViewBag.Title = "aaa";
    Layout = "../DefaultLayout/Index";
}

<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Müşteri Paneli</h3>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>CRM<small>Müşteriler</small></h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li>
                                <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="#">Settings 1</a>
                                    </li>
                                    <li>
                                        <a href="#">Settings 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <form class="form-horizontal form-label-left " method="post" novalidate>
                            <div class="section" style="margin: 5px;">
                                <h2>Müşterilerim</h2>
      
                                <table class="table">
                                    <tr>
                                        <th>
                                            Şirket Adı
                                        </th>
                                        <th>
                                            İletişim Kurulan Kişi
                                        </th>
                                        <th>
                                            Email adresi
                                        </th>
                                        <th>
                                            Telefon Numarası
                                        </th>
                                        <th>

                                        </th>
                                    </tr>
                                    
                                    @foreach (var item in Model )
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CompanyName)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.ContactPerson)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                                            </td>

                                            <td>
                                                @Html.ActionLink("Yeni Telif Ver", "AddSuggestion","Suggestion", new { Id = item.Id }) | 
                                                @Html.ActionLink("Bilgileri Düzenle", "EditCustomer", new { Id = item.Id })
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>